# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /sda3mnt/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /sda3mnt/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /sda3mnt/project/CMakeFiles /sda3mnt/project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /sda3mnt/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named serverV1

# Build rule for target.
serverV1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serverV1
.PHONY : serverV1

# fast build rule for target.
serverV1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/build
.PHONY : serverV1/fast

src/Chatserver/Mainserver.o: src/Chatserver/Mainserver.cpp.o
.PHONY : src/Chatserver/Mainserver.o

# target to build an object file
src/Chatserver/Mainserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Mainserver.cpp.o
.PHONY : src/Chatserver/Mainserver.cpp.o

src/Chatserver/Mainserver.i: src/Chatserver/Mainserver.cpp.i
.PHONY : src/Chatserver/Mainserver.i

# target to preprocess a source file
src/Chatserver/Mainserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Mainserver.cpp.i
.PHONY : src/Chatserver/Mainserver.cpp.i

src/Chatserver/Mainserver.s: src/Chatserver/Mainserver.cpp.s
.PHONY : src/Chatserver/Mainserver.s

# target to generate assembly for a file
src/Chatserver/Mainserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Mainserver.cpp.s
.PHONY : src/Chatserver/Mainserver.cpp.s

src/Chatserver/Myconn.o: src/Chatserver/Myconn.cpp.o
.PHONY : src/Chatserver/Myconn.o

# target to build an object file
src/Chatserver/Myconn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Myconn.cpp.o
.PHONY : src/Chatserver/Myconn.cpp.o

src/Chatserver/Myconn.i: src/Chatserver/Myconn.cpp.i
.PHONY : src/Chatserver/Myconn.i

# target to preprocess a source file
src/Chatserver/Myconn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Myconn.cpp.i
.PHONY : src/Chatserver/Myconn.cpp.i

src/Chatserver/Myconn.s: src/Chatserver/Myconn.cpp.s
.PHONY : src/Chatserver/Myconn.s

# target to generate assembly for a file
src/Chatserver/Myconn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Myconn.cpp.s
.PHONY : src/Chatserver/Myconn.cpp.s

src/Chatserver/Services.o: src/Chatserver/Services.cpp.o
.PHONY : src/Chatserver/Services.o

# target to build an object file
src/Chatserver/Services.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Services.cpp.o
.PHONY : src/Chatserver/Services.cpp.o

src/Chatserver/Services.i: src/Chatserver/Services.cpp.i
.PHONY : src/Chatserver/Services.i

# target to preprocess a source file
src/Chatserver/Services.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Services.cpp.i
.PHONY : src/Chatserver/Services.cpp.i

src/Chatserver/Services.s: src/Chatserver/Services.cpp.s
.PHONY : src/Chatserver/Services.s

# target to generate assembly for a file
src/Chatserver/Services.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Services.cpp.s
.PHONY : src/Chatserver/Services.cpp.s

src/Chatserver/Usermodel.o: src/Chatserver/Usermodel.cpp.o
.PHONY : src/Chatserver/Usermodel.o

# target to build an object file
src/Chatserver/Usermodel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Usermodel.cpp.o
.PHONY : src/Chatserver/Usermodel.cpp.o

src/Chatserver/Usermodel.i: src/Chatserver/Usermodel.cpp.i
.PHONY : src/Chatserver/Usermodel.i

# target to preprocess a source file
src/Chatserver/Usermodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Usermodel.cpp.i
.PHONY : src/Chatserver/Usermodel.cpp.i

src/Chatserver/Usermodel.s: src/Chatserver/Usermodel.cpp.s
.PHONY : src/Chatserver/Usermodel.s

# target to generate assembly for a file
src/Chatserver/Usermodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/Usermodel.cpp.s
.PHONY : src/Chatserver/Usermodel.cpp.s

src/Chatserver/main.o: src/Chatserver/main.cpp.o
.PHONY : src/Chatserver/main.o

# target to build an object file
src/Chatserver/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/main.cpp.o
.PHONY : src/Chatserver/main.cpp.o

src/Chatserver/main.i: src/Chatserver/main.cpp.i
.PHONY : src/Chatserver/main.i

# target to preprocess a source file
src/Chatserver/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/main.cpp.i
.PHONY : src/Chatserver/main.cpp.i

src/Chatserver/main.s: src/Chatserver/main.cpp.s
.PHONY : src/Chatserver/main.s

# target to generate assembly for a file
src/Chatserver/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Chatserver/main.cpp.s
.PHONY : src/Chatserver/main.cpp.s

src/Server/Acceptor.o: src/Server/Acceptor.cc.o
.PHONY : src/Server/Acceptor.o

# target to build an object file
src/Server/Acceptor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Acceptor.cc.o
.PHONY : src/Server/Acceptor.cc.o

src/Server/Acceptor.i: src/Server/Acceptor.cc.i
.PHONY : src/Server/Acceptor.i

# target to preprocess a source file
src/Server/Acceptor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Acceptor.cc.i
.PHONY : src/Server/Acceptor.cc.i

src/Server/Acceptor.s: src/Server/Acceptor.cc.s
.PHONY : src/Server/Acceptor.s

# target to generate assembly for a file
src/Server/Acceptor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Acceptor.cc.s
.PHONY : src/Server/Acceptor.cc.s

src/Server/Buffer.o: src/Server/Buffer.cc.o
.PHONY : src/Server/Buffer.o

# target to build an object file
src/Server/Buffer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Buffer.cc.o
.PHONY : src/Server/Buffer.cc.o

src/Server/Buffer.i: src/Server/Buffer.cc.i
.PHONY : src/Server/Buffer.i

# target to preprocess a source file
src/Server/Buffer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Buffer.cc.i
.PHONY : src/Server/Buffer.cc.i

src/Server/Buffer.s: src/Server/Buffer.cc.s
.PHONY : src/Server/Buffer.s

# target to generate assembly for a file
src/Server/Buffer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Buffer.cc.s
.PHONY : src/Server/Buffer.cc.s

src/Server/Channel.o: src/Server/Channel.cc.o
.PHONY : src/Server/Channel.o

# target to build an object file
src/Server/Channel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Channel.cc.o
.PHONY : src/Server/Channel.cc.o

src/Server/Channel.i: src/Server/Channel.cc.i
.PHONY : src/Server/Channel.i

# target to preprocess a source file
src/Server/Channel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Channel.cc.i
.PHONY : src/Server/Channel.cc.i

src/Server/Channel.s: src/Server/Channel.cc.s
.PHONY : src/Server/Channel.s

# target to generate assembly for a file
src/Server/Channel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Channel.cc.s
.PHONY : src/Server/Channel.cc.s

src/Server/CurrentThread.o: src/Server/CurrentThread.cc.o
.PHONY : src/Server/CurrentThread.o

# target to build an object file
src/Server/CurrentThread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/CurrentThread.cc.o
.PHONY : src/Server/CurrentThread.cc.o

src/Server/CurrentThread.i: src/Server/CurrentThread.cc.i
.PHONY : src/Server/CurrentThread.i

# target to preprocess a source file
src/Server/CurrentThread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/CurrentThread.cc.i
.PHONY : src/Server/CurrentThread.cc.i

src/Server/CurrentThread.s: src/Server/CurrentThread.cc.s
.PHONY : src/Server/CurrentThread.s

# target to generate assembly for a file
src/Server/CurrentThread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/CurrentThread.cc.s
.PHONY : src/Server/CurrentThread.cc.s

src/Server/EpollPoller.o: src/Server/EpollPoller.cc.o
.PHONY : src/Server/EpollPoller.o

# target to build an object file
src/Server/EpollPoller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EpollPoller.cc.o
.PHONY : src/Server/EpollPoller.cc.o

src/Server/EpollPoller.i: src/Server/EpollPoller.cc.i
.PHONY : src/Server/EpollPoller.i

# target to preprocess a source file
src/Server/EpollPoller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EpollPoller.cc.i
.PHONY : src/Server/EpollPoller.cc.i

src/Server/EpollPoller.s: src/Server/EpollPoller.cc.s
.PHONY : src/Server/EpollPoller.s

# target to generate assembly for a file
src/Server/EpollPoller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EpollPoller.cc.s
.PHONY : src/Server/EpollPoller.cc.s

src/Server/EventLoop.o: src/Server/EventLoop.cc.o
.PHONY : src/Server/EventLoop.o

# target to build an object file
src/Server/EventLoop.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoop.cc.o
.PHONY : src/Server/EventLoop.cc.o

src/Server/EventLoop.i: src/Server/EventLoop.cc.i
.PHONY : src/Server/EventLoop.i

# target to preprocess a source file
src/Server/EventLoop.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoop.cc.i
.PHONY : src/Server/EventLoop.cc.i

src/Server/EventLoop.s: src/Server/EventLoop.cc.s
.PHONY : src/Server/EventLoop.s

# target to generate assembly for a file
src/Server/EventLoop.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoop.cc.s
.PHONY : src/Server/EventLoop.cc.s

src/Server/EventLoopThread.o: src/Server/EventLoopThread.cc.o
.PHONY : src/Server/EventLoopThread.o

# target to build an object file
src/Server/EventLoopThread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoopThread.cc.o
.PHONY : src/Server/EventLoopThread.cc.o

src/Server/EventLoopThread.i: src/Server/EventLoopThread.cc.i
.PHONY : src/Server/EventLoopThread.i

# target to preprocess a source file
src/Server/EventLoopThread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoopThread.cc.i
.PHONY : src/Server/EventLoopThread.cc.i

src/Server/EventLoopThread.s: src/Server/EventLoopThread.cc.s
.PHONY : src/Server/EventLoopThread.s

# target to generate assembly for a file
src/Server/EventLoopThread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoopThread.cc.s
.PHONY : src/Server/EventLoopThread.cc.s

src/Server/EventLoopThreadPoll.o: src/Server/EventLoopThreadPoll.cc.o
.PHONY : src/Server/EventLoopThreadPoll.o

# target to build an object file
src/Server/EventLoopThreadPoll.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoopThreadPoll.cc.o
.PHONY : src/Server/EventLoopThreadPoll.cc.o

src/Server/EventLoopThreadPoll.i: src/Server/EventLoopThreadPoll.cc.i
.PHONY : src/Server/EventLoopThreadPoll.i

# target to preprocess a source file
src/Server/EventLoopThreadPoll.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoopThreadPoll.cc.i
.PHONY : src/Server/EventLoopThreadPoll.cc.i

src/Server/EventLoopThreadPoll.s: src/Server/EventLoopThreadPoll.cc.s
.PHONY : src/Server/EventLoopThreadPoll.s

# target to generate assembly for a file
src/Server/EventLoopThreadPoll.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/EventLoopThreadPoll.cc.s
.PHONY : src/Server/EventLoopThreadPoll.cc.s

src/Server/InetAddress.o: src/Server/InetAddress.cc.o
.PHONY : src/Server/InetAddress.o

# target to build an object file
src/Server/InetAddress.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/InetAddress.cc.o
.PHONY : src/Server/InetAddress.cc.o

src/Server/InetAddress.i: src/Server/InetAddress.cc.i
.PHONY : src/Server/InetAddress.i

# target to preprocess a source file
src/Server/InetAddress.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/InetAddress.cc.i
.PHONY : src/Server/InetAddress.cc.i

src/Server/InetAddress.s: src/Server/InetAddress.cc.s
.PHONY : src/Server/InetAddress.s

# target to generate assembly for a file
src/Server/InetAddress.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/InetAddress.cc.s
.PHONY : src/Server/InetAddress.cc.s

src/Server/Logger.o: src/Server/Logger.cc.o
.PHONY : src/Server/Logger.o

# target to build an object file
src/Server/Logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Logger.cc.o
.PHONY : src/Server/Logger.cc.o

src/Server/Logger.i: src/Server/Logger.cc.i
.PHONY : src/Server/Logger.i

# target to preprocess a source file
src/Server/Logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Logger.cc.i
.PHONY : src/Server/Logger.cc.i

src/Server/Logger.s: src/Server/Logger.cc.s
.PHONY : src/Server/Logger.s

# target to generate assembly for a file
src/Server/Logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Logger.cc.s
.PHONY : src/Server/Logger.cc.s

src/Server/Poller.o: src/Server/Poller.cc.o
.PHONY : src/Server/Poller.o

# target to build an object file
src/Server/Poller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Poller.cc.o
.PHONY : src/Server/Poller.cc.o

src/Server/Poller.i: src/Server/Poller.cc.i
.PHONY : src/Server/Poller.i

# target to preprocess a source file
src/Server/Poller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Poller.cc.i
.PHONY : src/Server/Poller.cc.i

src/Server/Poller.s: src/Server/Poller.cc.s
.PHONY : src/Server/Poller.s

# target to generate assembly for a file
src/Server/Poller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Poller.cc.s
.PHONY : src/Server/Poller.cc.s

src/Server/Socket.o: src/Server/Socket.cc.o
.PHONY : src/Server/Socket.o

# target to build an object file
src/Server/Socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Socket.cc.o
.PHONY : src/Server/Socket.cc.o

src/Server/Socket.i: src/Server/Socket.cc.i
.PHONY : src/Server/Socket.i

# target to preprocess a source file
src/Server/Socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Socket.cc.i
.PHONY : src/Server/Socket.cc.i

src/Server/Socket.s: src/Server/Socket.cc.s
.PHONY : src/Server/Socket.s

# target to generate assembly for a file
src/Server/Socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Socket.cc.s
.PHONY : src/Server/Socket.cc.s

src/Server/TcpConnection.o: src/Server/TcpConnection.cc.o
.PHONY : src/Server/TcpConnection.o

# target to build an object file
src/Server/TcpConnection.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/TcpConnection.cc.o
.PHONY : src/Server/TcpConnection.cc.o

src/Server/TcpConnection.i: src/Server/TcpConnection.cc.i
.PHONY : src/Server/TcpConnection.i

# target to preprocess a source file
src/Server/TcpConnection.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/TcpConnection.cc.i
.PHONY : src/Server/TcpConnection.cc.i

src/Server/TcpConnection.s: src/Server/TcpConnection.cc.s
.PHONY : src/Server/TcpConnection.s

# target to generate assembly for a file
src/Server/TcpConnection.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/TcpConnection.cc.s
.PHONY : src/Server/TcpConnection.cc.s

src/Server/TcpServer.o: src/Server/TcpServer.cc.o
.PHONY : src/Server/TcpServer.o

# target to build an object file
src/Server/TcpServer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/TcpServer.cc.o
.PHONY : src/Server/TcpServer.cc.o

src/Server/TcpServer.i: src/Server/TcpServer.cc.i
.PHONY : src/Server/TcpServer.i

# target to preprocess a source file
src/Server/TcpServer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/TcpServer.cc.i
.PHONY : src/Server/TcpServer.cc.i

src/Server/TcpServer.s: src/Server/TcpServer.cc.s
.PHONY : src/Server/TcpServer.s

# target to generate assembly for a file
src/Server/TcpServer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/TcpServer.cc.s
.PHONY : src/Server/TcpServer.cc.s

src/Server/Thread.o: src/Server/Thread.cc.o
.PHONY : src/Server/Thread.o

# target to build an object file
src/Server/Thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Thread.cc.o
.PHONY : src/Server/Thread.cc.o

src/Server/Thread.i: src/Server/Thread.cc.i
.PHONY : src/Server/Thread.i

# target to preprocess a source file
src/Server/Thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Thread.cc.i
.PHONY : src/Server/Thread.cc.i

src/Server/Thread.s: src/Server/Thread.cc.s
.PHONY : src/Server/Thread.s

# target to generate assembly for a file
src/Server/Thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Thread.cc.s
.PHONY : src/Server/Thread.cc.s

src/Server/Timestamp.o: src/Server/Timestamp.cc.o
.PHONY : src/Server/Timestamp.o

# target to build an object file
src/Server/Timestamp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Timestamp.cc.o
.PHONY : src/Server/Timestamp.cc.o

src/Server/Timestamp.i: src/Server/Timestamp.cc.i
.PHONY : src/Server/Timestamp.i

# target to preprocess a source file
src/Server/Timestamp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Timestamp.cc.i
.PHONY : src/Server/Timestamp.cc.i

src/Server/Timestamp.s: src/Server/Timestamp.cc.s
.PHONY : src/Server/Timestamp.s

# target to generate assembly for a file
src/Server/Timestamp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/Timestamp.cc.s
.PHONY : src/Server/Timestamp.cc.s

src/Server/logtest.o: src/Server/logtest.cc.o
.PHONY : src/Server/logtest.o

# target to build an object file
src/Server/logtest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/logtest.cc.o
.PHONY : src/Server/logtest.cc.o

src/Server/logtest.i: src/Server/logtest.cc.i
.PHONY : src/Server/logtest.i

# target to preprocess a source file
src/Server/logtest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/logtest.cc.i
.PHONY : src/Server/logtest.cc.i

src/Server/logtest.s: src/Server/logtest.cc.s
.PHONY : src/Server/logtest.s

# target to generate assembly for a file
src/Server/logtest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serverV1.dir/build.make CMakeFiles/serverV1.dir/src/Server/logtest.cc.s
.PHONY : src/Server/logtest.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... serverV1"
	@echo "... src/Chatserver/Mainserver.o"
	@echo "... src/Chatserver/Mainserver.i"
	@echo "... src/Chatserver/Mainserver.s"
	@echo "... src/Chatserver/Myconn.o"
	@echo "... src/Chatserver/Myconn.i"
	@echo "... src/Chatserver/Myconn.s"
	@echo "... src/Chatserver/Services.o"
	@echo "... src/Chatserver/Services.i"
	@echo "... src/Chatserver/Services.s"
	@echo "... src/Chatserver/Usermodel.o"
	@echo "... src/Chatserver/Usermodel.i"
	@echo "... src/Chatserver/Usermodel.s"
	@echo "... src/Chatserver/main.o"
	@echo "... src/Chatserver/main.i"
	@echo "... src/Chatserver/main.s"
	@echo "... src/Server/Acceptor.o"
	@echo "... src/Server/Acceptor.i"
	@echo "... src/Server/Acceptor.s"
	@echo "... src/Server/Buffer.o"
	@echo "... src/Server/Buffer.i"
	@echo "... src/Server/Buffer.s"
	@echo "... src/Server/Channel.o"
	@echo "... src/Server/Channel.i"
	@echo "... src/Server/Channel.s"
	@echo "... src/Server/CurrentThread.o"
	@echo "... src/Server/CurrentThread.i"
	@echo "... src/Server/CurrentThread.s"
	@echo "... src/Server/EpollPoller.o"
	@echo "... src/Server/EpollPoller.i"
	@echo "... src/Server/EpollPoller.s"
	@echo "... src/Server/EventLoop.o"
	@echo "... src/Server/EventLoop.i"
	@echo "... src/Server/EventLoop.s"
	@echo "... src/Server/EventLoopThread.o"
	@echo "... src/Server/EventLoopThread.i"
	@echo "... src/Server/EventLoopThread.s"
	@echo "... src/Server/EventLoopThreadPoll.o"
	@echo "... src/Server/EventLoopThreadPoll.i"
	@echo "... src/Server/EventLoopThreadPoll.s"
	@echo "... src/Server/InetAddress.o"
	@echo "... src/Server/InetAddress.i"
	@echo "... src/Server/InetAddress.s"
	@echo "... src/Server/Logger.o"
	@echo "... src/Server/Logger.i"
	@echo "... src/Server/Logger.s"
	@echo "... src/Server/Poller.o"
	@echo "... src/Server/Poller.i"
	@echo "... src/Server/Poller.s"
	@echo "... src/Server/Socket.o"
	@echo "... src/Server/Socket.i"
	@echo "... src/Server/Socket.s"
	@echo "... src/Server/TcpConnection.o"
	@echo "... src/Server/TcpConnection.i"
	@echo "... src/Server/TcpConnection.s"
	@echo "... src/Server/TcpServer.o"
	@echo "... src/Server/TcpServer.i"
	@echo "... src/Server/TcpServer.s"
	@echo "... src/Server/Thread.o"
	@echo "... src/Server/Thread.i"
	@echo "... src/Server/Thread.s"
	@echo "... src/Server/Timestamp.o"
	@echo "... src/Server/Timestamp.i"
	@echo "... src/Server/Timestamp.s"
	@echo "... src/Server/logtest.o"
	@echo "... src/Server/logtest.i"
	@echo "... src/Server/logtest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

